targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/domain/entity/*.dart
            - lib/domain/store/*.dart
            - lib/ui/screen_model/*.dart