targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/domain/*.dart
            - lib/entity/*.dart
            - lib/selection/*.dart
            - lib/ui/screen_model/*.dart